services:
  - type: web
    name: rideapp-logger1
    env: static
    buildCommand: ""
    staticPublishPath: .
    routes:
      - type: rewrite
        source: /*
<<<<<<< HEAD
        destination: /index.html
=======
        destination: /rideLogger.html
>>>>>>> 3d3f03880da66ec27c47517c5072a9550bc93e67
